window.dashboardData = {
  refreshedAt: "2026-04-09 17:27:56 UTC",
  workbook: "20260323 EMEA Org Design Analysis FY26",
  takeaways: [
    "Overall current coverage is 54.0%; recommended coverage rises to 71.8%.",
    "Biggest account whitespace territories are UKI (+373), Germany (+185), France (+184).",
    "Lowest-covered geo is MEA at 42.3% vs North at 59.1%.",
    "Weakest geo/segment cut is MEA Enterprise at 18.1%."
  ],
  summary: {
    totalAccounts: 8413,
    accountsInBooks: 4543,
    currentCoverage: 0.5399976227,
    recommendedCoverage: 0.718495186,
    coverageGap: 0.1784975633,
    incrementalAccounts: 1501.7,
    recommendedAds: 111,
    targetAccountsPerAd: 54.45675676,
    bookArr: 322312279.57,
    customers: 843,
    managers: 16
  },
  mustWin: {
    "generatedAt": "2026-04-16 19:14:23 UTC",
    "updatedAt": "2026-04-16",
    "status": "Fresh via Kepler",
    "source": "Kepler live query over gtm.prod.agg_sfdc_account_daily and gtm.prod.dim_sfdc_account",
    "sourcePath": "Kepler dashboard c026476b-c77e-4c03-92a9-dc8e03548002",
    "sourceUpdatedAt": "2026-04-16",
    "sourceGeneratedAt": "2026-04-16 19:14:23 UTC",
    "latestReportingDate": "2026-04-14",
    "fullDashboardPath": "../emea-must-win-dashboard/index.html",
    "summary": {
        "accountsInScope": 100,
        "activeAccounts": 100,
        "currentArrUsd": 100610415,
        "targetArrUsd": 0,
        "arrQoqGrowthUsd": null,
        "arrQoqGrowthPct": null,
        "arrYoyGrowthUsd": null,
        "arrYoyGrowthPct": null,
        "openPipelineUsd": 26211745,
        "commitUsd": 0,
        "bestCaseUsd": 0,
        "loadedArrAccounts": 100,
        "loadedUsageAccounts": 0,
        "ownersLoaded": 100,
        "sponsorsLoaded": 100,
        "latestArrSnapshot": "2026-04-14",
        "latestPipelineSnapshot": "2026-04-14"
    },
    "countryPipeline": [
        {
            "country": "United Kingdom",
            "accounts": 20,
            "arr": 9224474.0,
            "pipeline": 4857868.0
        },
        {
            "country": "Germany",
            "accounts": 14,
            "arr": 6048282.0,
            "pipeline": 5900000.0
        },
        {
            "country": "Israel",
            "accounts": 9,
            "arr": 3506997.0,
            "pipeline": 656420.0
        },
        {
            "country": "United States of America",
            "accounts": 9,
            "arr": 1578484.0,
            "pipeline": 1900000.0
        },
        {
            "country": "Netherlands",
            "accounts": 7,
            "arr": 4276771.0,
            "pipeline": 350960.0
        },
        {
            "country": "France",
            "accounts": 6,
            "arr": 4147045.0,
            "pipeline": 5000000.0
        },
        {
            "country": "Switzerland",
            "accounts": 6,
            "arr": 3306577.0,
            "pipeline": 5615233.0
        },
        {
            "country": "Sweden",
            "accounts": 5,
            "arr": 45205099.0,
            "pipeline": 1931264.0
        },
        {
            "country": "Spain",
            "accounts": 4,
            "arr": 13152646.0,
            "pipeline": 0.0
        },
        {
            "country": "United Arab Emirates",
            "accounts": 4,
            "arr": 435641.0,
            "pipeline": 0.0
        },
        {
            "country": "Austria",
            "accounts": 2,
            "arr": 263640.0,
            "pipeline": 0.0
        },
        {
            "country": "Denmark",
            "accounts": 2,
            "arr": 967924.0,
            "pipeline": 0.0
        },
        {
            "country": "Finland",
            "accounts": 2,
            "arr": 178201.0,
            "pipeline": 0.0
        },
        {
            "country": "Bahrain",
            "accounts": 1,
            "arr": 432000.0,
            "pipeline": 0.0
        },
        {
            "country": "Belgium",
            "accounts": 1,
            "arr": 522247.0,
            "pipeline": 0.0
        },
        {
            "country": "Canada",
            "accounts": 1,
            "arr": 39600.0,
            "pipeline": 0.0
        },
        {
            "country": "Cyprus",
            "accounts": 1,
            "arr": 139354.0,
            "pipeline": 0.0
        },
        {
            "country": "Czechia",
            "accounts": 1,
            "arr": 6167987.0,
            "pipeline": 0.0
        },
        {
            "country": "Italy",
            "accounts": 1,
            "arr": 24000.0,
            "pipeline": 0.0
        },
        {
            "country": "Norway",
            "accounts": 1,
            "arr": 148680.0,
            "pipeline": 0.0
        },
        {
            "country": "Poland",
            "accounts": 1,
            "arr": 325070.0,
            "pipeline": 0.0
        },
        {
            "country": "Singapore",
            "accounts": 1,
            "arr": 282096.0,
            "pipeline": 0.0
        },
        {
            "country": "Türkiye",
            "accounts": 1,
            "arr": 237600.0,
            "pipeline": 0.0
        }
    ],
    "priorityBuckets": [
        {
            "bucket": "MM Top Expansion",
            "accounts": 51,
            "arr": 16028434.0,
            "pipeline": 558068.0
        },
        {
            "bucket": "API Pursuits Target",
            "accounts": 35,
            "arr": 15568230.0,
            "pipeline": 11947580.0
        },
        {
            "bucket": "Top 10",
            "accounts": 14,
            "arr": 69013751.0,
            "pipeline": 13706097.0
        }
    ],
    "accounts": [
        {
            "accountId": "0014X00002XEJdnQAH",
            "rank": 1,
            "name": "Spotify",
            "bucket": "Top 10",
            "country": "Sweden",
            "segment": "Digital Natives",
            "vertical": "Other",
            "owner": "Julian Brophy",
            "execSponsor": "Phil Watson",
            "arr": 32019649,
            "pipeline": 0,
            "quarter": "Owned since 2023-02-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "G2K;API Pursuits Target;Top 10;Customer Stories/Advocate Pipeline;Codex Priority",
            "competitiveRisk": "Unknown",
            "flags": [
                "Rank changed 45 to 1",
                "Priority changed Scale 20 to Top 10",
                "ARR changed $17M to $32M",
                "Pipeline changed $13M to $0"
            ]
        },
        {
            "accountId": "0015e00000qeiyaAAA",
            "rank": 2,
            "name": "Klarna Bank AB",
            "bucket": "Top 10",
            "country": "Sweden",
            "segment": "Digital Natives",
            "vertical": "Technology & Software Development",
            "owner": "Emma McGuire",
            "execSponsor": "Phil Watson",
            "arr": 11409450,
            "pipeline": 1931264,
            "quarter": "2026-08-25 — Renewal [2026] - Klarna - 2025 Renewal API",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target;Top 10",
            "competitiveRisk": "Anthropic",
            "flags": []
        },
        {
            "accountId": "0015e00000SkPtJAAV",
            "rank": 3,
            "name": "Booking.com B.V.",
            "bucket": "Top 10",
            "country": "Netherlands",
            "segment": "Digital Natives",
            "vertical": "Technology & Software Development",
            "owner": "Julian Brophy",
            "execSponsor": "Phil Watson",
            "arr": 2301057,
            "pipeline": 0,
            "quarter": "Owned since 2024-01-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "G2K;API Pursuits Target;Top 10",
            "competitiveRisk": "Google",
            "flags": []
        },
        {
            "accountId": "001VU000001a8T7YAI",
            "rank": 4,
            "name": "Octapharma AG",
            "bucket": "Top 10",
            "country": "Switzerland",
            "segment": "Enterprise",
            "vertical": "Healthcare & Life Sciences",
            "owner": "Jovana Jordanova",
            "execSponsor": "Nico Skabo",
            "arr": 300001,
            "pipeline": 0,
            "quarter": "Owned since 2025-05-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion;Top 100 Pharmaceuticals - 2025",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000H4gyDYAR",
            "rank": 5,
            "name": "Novocure Inc.",
            "bucket": "Top 10",
            "country": "United States of America",
            "segment": "Mid-Market",
            "vertical": "Manufacturing / Construction",
            "owner": "Johannes Foertsch",
            "execSponsor": "Orian English",
            "arr": 170426,
            "pipeline": 309600,
            "quarter": "2027-01-31 — Renewal [2027] - Renewal [2026] - Novocure - ChatGPT Enterprise",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion;Top 100 Medtech - 2025",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000V4LDEAA3",
            "rank": 6,
            "name": "Philips Electronics Nederland B.V.",
            "bucket": "Top 10",
            "country": "Netherlands",
            "segment": "Enterprise",
            "vertical": "Healthcare & Life Sciences",
            "owner": "Stephanie Tran",
            "execSponsor": "Nico Skabo",
            "arr": 1202824,
            "pipeline": 350000,
            "quarter": "2026-05-18 — Renewal [2026] - Philips-NB-ChatGPT Enterprise (land)",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "G2K;Customer Stories/Advocate Pipeline;Top 100 Medtech - 2025;Codex Priority",
            "competitiveRisk": "Azure OpenAI Service",
            "flags": []
        },
        {
            "accountId": "0015e00000LVe7BAAT",
            "rank": 7,
            "name": "Santander Global Technology and Operations, S.L.U.",
            "bucket": "Top 10",
            "country": "Spain",
            "segment": "Enterprise",
            "vertical": "Financial Services",
            "owner": "Rikki Gorman",
            "execSponsor": "Nico Skabo",
            "arr": 12779206,
            "pipeline": 0,
            "quarter": "Owned since 2024-12-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "G2K;Top 10;Customer Stories/Advocate Pipeline;Fortune Global 500 - 2025",
            "competitiveRisk": "Azure OpenAI Service",
            "flags": [
                "Source sheet note: strategic_emea_entity"
            ]
        },
        {
            "accountId": "0015e00000V3j42AAB",
            "rank": 8,
            "name": "JetBrains s.r.o.",
            "bucket": "Top 10",
            "country": "Czechia",
            "segment": "Digital Natives",
            "vertical": "Technology & Software Development",
            "owner": "Julian Brophy",
            "execSponsor": "Phil Watson",
            "arr": 6167987,
            "pipeline": 0,
            "quarter": "Owned since 2023-06-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "Top 10",
            "competitiveRisk": "Google",
            "flags": []
        },
        {
            "accountId": "0015e00000SiatbAAB",
            "rank": 9,
            "name": "Genentech",
            "bucket": "Top 10",
            "country": "Switzerland",
            "segment": "Enterprise",
            "vertical": "Healthcare & Life Sciences",
            "owner": "Jovana Jordanova",
            "execSponsor": "Nico Skabo",
            "arr": 2280519,
            "pipeline": 5388433,
            "quarter": "2026-04-30 — Roche API Consumption - Early development, PD and Clinical Development",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "G2K;Healthcare Vertical;Customer Stories/Advocate Pipeline;Top 100 Pharmaceuticals - 2025;Fortune Global 500 - 2025",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000CapzZYAR",
            "rank": 10,
            "name": "Institut Straumann AG",
            "bucket": "Top 10",
            "country": "Switzerland",
            "segment": "Enterprise",
            "vertical": "Healthcare & Life Sciences",
            "owner": "Jovana Jordanova",
            "execSponsor": "Nico Skabo",
            "arr": 333290,
            "pipeline": 226800,
            "quarter": "2026-05-22 — Renewal [2026] - Institut Straumann - Upsell - Sales Led Expansion",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "Top 100 Medtech - 2025",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000Hs8WgYAJ",
            "rank": 11,
            "name": "Menarini I.F.R srl",
            "bucket": "Top 10",
            "country": "Italy",
            "segment": "Enterprise",
            "vertical": "Healthcare & Life Sciences",
            "owner": "William Louis Joseph Dogue",
            "execSponsor": "François Weider",
            "arr": 24000,
            "pipeline": 0,
            "quarter": "2026-04-21 — Renewal [2026] - Menarini- ChatGPT Enterprise",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "Top 100 Pharmaceuticals - 2025",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000cjHwtAAE",
            "rank": 12,
            "name": "Novo Nordisk",
            "bucket": "Top 10",
            "country": "Denmark",
            "segment": "Enterprise",
            "vertical": "Healthcare & Life Sciences",
            "owner": "Joe Welton",
            "execSponsor": "Nico Skabo",
            "arr": 23824,
            "pipeline": 0,
            "quarter": "Owned since 2025-02-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "G2K;Top 10;Healthcare Vertical;Customer Stories/Advocate Pipeline;Top 100 Pharmaceuticals - 2025",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000cjEB5AAM",
            "rank": 13,
            "name": "Merck KGaA (EMD Group)",
            "bucket": "Top 10",
            "country": "Germany",
            "segment": "Enterprise",
            "vertical": "Healthcare & Life Sciences",
            "owner": "Christoph Winter",
            "execSponsor": "Nico Skabo",
            "arr": 1130,
            "pipeline": 500000,
            "quarter": "2026-06-23 — Merck - API Migration Azure",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "G2K;Top 100 Pharmaceuticals - 2025",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000gLytPAAS",
            "rank": 14,
            "name": "Sanofi Winthrop Industrie (“Sanofi”) | Parent account",
            "bucket": "Top 10",
            "country": "France",
            "segment": "Enterprise",
            "vertical": "Healthcare & Life Sciences",
            "owner": "Matthieu Fouchard",
            "execSponsor": "François Weider",
            "arr": 388,
            "pipeline": 5000000,
            "quarter": "2026-07-31 — Sanofi Winthrop Industrie (“Sanofi”) - Referral - Boston Consulting Group (Partner - Global)",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "G2K;Healthcare Vertical;Top 100 Pharmaceuticals - 2025;Fortune Global 500 - 2025",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0014X00002grkijQAA",
            "rank": 15,
            "name": "Sofigate Oy",
            "bucket": "API Pursuits Target",
            "country": "Finland",
            "segment": "Mid-Market",
            "vertical": "Business & Professional Services",
            "owner": "Helena Bunney",
            "execSponsor": "Orian English",
            "arr": 158400,
            "pipeline": 0,
            "quarter": "Owned since 2025-11-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target;API Pursuits Target;MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000CoHbYYAV",
            "rank": 16,
            "name": "Travelport LP",
            "bucket": "API Pursuits Target",
            "country": "United States of America",
            "segment": "Mid-Market",
            "vertical": "Technology & Software Development",
            "owner": "Sean McKeon",
            "execSponsor": "Orian English",
            "arr": 37800,
            "pipeline": 0,
            "quarter": "Owned since 2026-03-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target;MM Top Prospect",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000Sl5D1AAJ",
            "rank": 17,
            "name": "Endava",
            "bucket": "API Pursuits Target",
            "country": "United Kingdom",
            "segment": "Enterprise",
            "vertical": "Technology & Software Development",
            "owner": "Maire OHerlihy",
            "execSponsor": "Folley Ogundele",
            "arr": 4320000,
            "pipeline": 4320360,
            "quarter": "2026-07-01 — Endava - Renewal - ChatGPT 2026",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000gLtMVAA0",
            "rank": 18,
            "name": "monday.com",
            "bucket": "API Pursuits Target",
            "country": "Israel",
            "segment": "Digital Natives",
            "vertical": "Technology & Software Development",
            "owner": "Claire Harrington",
            "execSponsor": "Phil Watson",
            "arr": 1729636,
            "pipeline": 0,
            "quarter": "2026-04-30 — Renewal [2026] - Renewal 2026 - Monday.com - ChatGPT",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000q6u36AAA",
            "rank": 19,
            "name": "Zalando SE",
            "bucket": "API Pursuits Target",
            "country": "Germany",
            "segment": "Digital Natives",
            "vertical": "Media & Telecom",
            "owner": "Tilman Resch",
            "execSponsor": "Phil Watson",
            "arr": 1664889,
            "pipeline": 0,
            "quarter": "Owned since 2023-04-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Anthropic",
            "flags": []
        },
        {
            "accountId": "0014X00002hju1aQAA",
            "rank": 20,
            "name": "SCHIBSTED MEDIA PRODUCTS & TECHNOLOGY AS",
            "bucket": "API Pursuits Target",
            "country": "Sweden",
            "segment": "Mid-Market",
            "vertical": "Technology & Software Development",
            "owner": "Orian English",
            "execSponsor": "Sanj Bhayro",
            "arr": 1512000,
            "pipeline": 0,
            "quarter": "Owned since 2024-03-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "G2K;API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000ousdMAAQ",
            "rank": 21,
            "name": "GetYourGuide Deutschland GmbH",
            "bucket": "API Pursuits Target",
            "country": "Germany",
            "segment": "Digital Natives",
            "vertical": "Technology & Software Development",
            "owner": "Niklas Harzheim",
            "execSponsor": "Clement Andre",
            "arr": 882408,
            "pipeline": 750000,
            "quarter": "2026-05-15 — Early Renewal [2026] - Get Your Guide - $1M API Commitment ; 750k icarr",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000V4VxBAAV",
            "rank": 22,
            "name": "Taboola.com LTD",
            "bucket": "API Pursuits Target",
            "country": "Israel",
            "segment": "Digital Natives",
            "vertical": "Technology & Software Development",
            "owner": "Claire Harrington",
            "execSponsor": "Phil Watson",
            "arr": 585921,
            "pipeline": 0,
            "quarter": "Owned since 2024-02-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU0000093iIlYAI",
            "rank": 23,
            "name": "Check Point Software Technologies Ltd.",
            "bucket": "API Pursuits Target",
            "country": "United States of America",
            "segment": "Digital Natives",
            "vertical": "Technology & Software Development",
            "owner": "Roz Gibson",
            "execSponsor": "Phil Watson",
            "arr": 570240,
            "pipeline": 590400,
            "quarter": "2026-05-06 — Check Point - OAI on Azure Migration",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "G2K;API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000gL6qGAAS",
            "rank": 24,
            "name": "Celonis, Inc.",
            "bucket": "API Pursuits Target",
            "country": "Germany",
            "segment": "Digital Natives",
            "vertical": "Technology & Software Development",
            "owner": "Tilman Resch",
            "execSponsor": "Phil Watson",
            "arr": 482489,
            "pipeline": 3900000,
            "quarter": "2026-05-15 — Celonis, Inc - Win API consumption from Azure and Frontier",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000CoMCwYAN",
            "rank": 25,
            "name": "Trainline",
            "bucket": "API Pursuits Target",
            "country": "United Kingdom",
            "segment": "Digital Natives",
            "vertical": "Business & Professional Services",
            "owner": "Claire Harrington",
            "execSponsor": "Phil Watson",
            "arr": 406726,
            "pipeline": 0,
            "quarter": "Owned since 2025-07-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU000005QHK5YAO",
            "rank": 26,
            "name": "Shop Apotheke Service B.V.",
            "bucket": "API Pursuits Target",
            "country": "Netherlands",
            "segment": "Mid-Market",
            "vertical": "Healthcare & Life Sciences",
            "owner": "John Shanahan",
            "execSponsor": "Orian English",
            "arr": 336000,
            "pipeline": 0,
            "quarter": "Owned since 2025-04-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000q6zjuAAA",
            "rank": 27,
            "name": "Contentful, Inc.",
            "bucket": "API Pursuits Target",
            "country": "United States of America",
            "segment": "Digital Natives",
            "vertical": "Technology & Software Development",
            "owner": "Tilman Resch",
            "execSponsor": "Phil Watson",
            "arr": 328811,
            "pipeline": 1000000,
            "quarter": "2026-04-28 — Contentful - Win API Consumption and Strategic Collaboration",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000qegF4AAI",
            "rank": 28,
            "name": "CD PROJEKT S.A.",
            "bucket": "API Pursuits Target",
            "country": "Poland",
            "segment": "Mid-Market",
            "vertical": "Media & Telecom",
            "owner": "Helena Bunney",
            "execSponsor": "Orian English",
            "arr": 325070,
            "pipeline": 0,
            "quarter": "Owned since 2024-12-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000HXFbBYAX",
            "rank": 29,
            "name": "Global Fashion Group SGP Services Pte. Ltd.",
            "bucket": "API Pursuits Target",
            "country": "Singapore",
            "segment": "Digital Natives",
            "vertical": "Business & Professional Services",
            "owner": "Orian English",
            "execSponsor": "Sanj Bhayro",
            "arr": 282096,
            "pipeline": 0,
            "quarter": "Owned since 2025-03-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000qdUA0AAM",
            "rank": 30,
            "name": "Playtika LTD",
            "bucket": "API Pursuits Target",
            "country": "Israel",
            "segment": "Digital Natives",
            "vertical": "Media & Telecom",
            "owner": "Roz Gibson",
            "execSponsor": "Phil Watson",
            "arr": 275040,
            "pipeline": 0,
            "quarter": "2026-05-11 — Renewal [2026] - Playtika ChatGPT Ent",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000qcQfKAAU",
            "rank": 31,
            "name": "Delivery Hero",
            "bucket": "API Pursuits Target",
            "country": "Germany",
            "segment": "Digital Natives",
            "vertical": "Business & Professional Services",
            "owner": "Tilman Resch",
            "execSponsor": "Phil Watson",
            "arr": 265457,
            "pipeline": 750000,
            "quarter": "2026-07-08 — Delivery Hero - $750M API Commitment Approach",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "G2K;API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": [
                "Rank changed 71 to 31",
                "Priority changed Build 15 to API Pursuits Target",
                "ARR changed $572K to $265K",
                "Pipeline changed $1M to $750K"
            ]
        },
        {
            "accountId": "001VU0000034VefYAE",
            "rank": 32,
            "name": "Moonpig.com Limited",
            "bucket": "API Pursuits Target",
            "country": "United Kingdom",
            "segment": "Digital Natives",
            "vertical": "Technology & Software Development",
            "owner": "Julian Brophy",
            "execSponsor": "Phil Watson",
            "arr": 203423,
            "pipeline": 0,
            "quarter": "Owned since 2025-09-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000QaslSAAR",
            "rank": 33,
            "name": "Fiverr International Ltd",
            "bucket": "API Pursuits Target",
            "country": "Israel",
            "segment": "Digital Natives",
            "vertical": "Technology & Software Development",
            "owner": "Roz Gibson",
            "execSponsor": "Phil Watson",
            "arr": 190291,
            "pipeline": 0,
            "quarter": "Owned since 2025-02-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000V1SKOAA3",
            "rank": 34,
            "name": "Vimeo.com, Inc.",
            "bucket": "API Pursuits Target",
            "country": "United States of America",
            "segment": "Digital Natives",
            "vertical": "Technology & Software Development",
            "owner": "Julien Simiand",
            "execSponsor": "Clement Andre",
            "arr": 180033,
            "pipeline": 0,
            "quarter": "2026-05-30 — Renewal [2026] - Vimeo - ChatGPT",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000SkikuAAB",
            "rank": 35,
            "name": "Cimpress Schweiz GmbH",
            "bucket": "API Pursuits Target",
            "country": "Switzerland",
            "segment": "Enterprise",
            "vertical": "Business & Professional Services",
            "owner": "Tilman Resch",
            "execSponsor": "Phil Watson",
            "arr": 147960,
            "pipeline": 0,
            "quarter": "Owned since 2025-09-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000CoHreYAF",
            "rank": 36,
            "name": "Rapyd Financial Network Ltd",
            "bucket": "API Pursuits Target",
            "country": "United Kingdom",
            "segment": "Digital Natives",
            "vertical": "Financial Services",
            "owner": "Julian Brophy",
            "execSponsor": "Phil Watson",
            "arr": 107665,
            "pipeline": 0,
            "quarter": "Owned since 2024-12-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0014X00002iG0l9QAC",
            "rank": 37,
            "name": "CELLEBRITE DI LTD",
            "bucket": "API Pursuits Target",
            "country": "United States of America",
            "segment": "Government",
            "vertical": "Pubsec",
            "owner": "Claire Trithardt",
            "execSponsor": "Orian English",
            "arr": 96000,
            "pipeline": 0,
            "quarter": "Owned since 2025-09-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000qeh72AAA",
            "rank": 38,
            "name": "Checkout Technology Ltd",
            "bucket": "API Pursuits Target",
            "country": "United Kingdom",
            "segment": "Digital Natives",
            "vertical": "Financial Services",
            "owner": "Hilary Platt",
            "execSponsor": "Clement Andre",
            "arr": 79327,
            "pipeline": 230400,
            "quarter": "2026-06-26 — Checkout - Cross Sell - Codex",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000MxMKtYAN",
            "rank": 39,
            "name": "The Hut Group - THG",
            "bucket": "API Pursuits Target",
            "country": "United Kingdom",
            "segment": "Mid-Market",
            "vertical": "Technology & Software Development",
            "owner": "Hilary Platt",
            "execSponsor": "Clement Andre",
            "arr": 71757,
            "pipeline": 250000,
            "quarter": "2026-06-25 — THG (The Hut Group) - API Commitment",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU000005fBe9YAE",
            "rank": 40,
            "name": "Riskified LTD",
            "bucket": "API Pursuits Target",
            "country": "Israel",
            "segment": "Digital Natives",
            "vertical": "Technology & Software Development",
            "owner": "Roz Gibson",
            "execSponsor": "Phil Watson",
            "arr": 68401,
            "pipeline": 0,
            "quarter": "Owned since 2025-11-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000CoJi7YAF",
            "rank": 41,
            "name": "Delticom AG",
            "bucket": "API Pursuits Target",
            "country": "Germany",
            "segment": "Startups",
            "vertical": "Manufacturing / Construction",
            "owner": "Amaury de Longvilliers",
            "execSponsor": "Chris Brown",
            "arr": 67177,
            "pipeline": 0,
            "quarter": "Owned since 2025-05-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000BnPuzYAF",
            "rank": 42,
            "name": "WalkMe Ltd",
            "bucket": "API Pursuits Target",
            "country": "Israel",
            "segment": "Enterprise",
            "vertical": "Technology & Software Development",
            "owner": "William Louis Joseph Dogue",
            "execSponsor": "François Weider",
            "arr": 43940,
            "pipeline": 0,
            "quarter": "Owned since 2025-02-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000U5E9DYAV",
            "rank": 43,
            "name": "Cognyte Technologies Israel Ltd",
            "bucket": "API Pursuits Target",
            "country": "Israel",
            "segment": "Digital Natives",
            "vertical": "Technology & Software Development",
            "owner": "Claire Harrington",
            "execSponsor": "Phil Watson",
            "arr": 43560,
            "pipeline": 156420,
            "quarter": "2026-10-31 — Renewal [2026] - Cognyte Technologies Israel Ltd - ChatGPT Upsell",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000CoLs4YAF",
            "rank": 44,
            "name": "ODDITY Tech LTD",
            "bucket": "API Pursuits Target",
            "country": "United States of America",
            "segment": "Digital Natives",
            "vertical": "Business & Professional Services",
            "owner": "Roz Gibson",
            "execSponsor": "Phil Watson",
            "arr": 34848,
            "pipeline": 0,
            "quarter": "Owned since 2025-10-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0014X00002dlCllQAE",
            "rank": 45,
            "name": "Adevinta Information Services, S.L.U.",
            "bucket": "API Pursuits Target",
            "country": "Netherlands",
            "segment": "Digital Natives",
            "vertical": "Business & Professional Services",
            "owner": "Emma McGuire",
            "execSponsor": "Phil Watson",
            "arr": 30972,
            "pipeline": 0,
            "quarter": "Owned since 2025-07-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU000000TdfVYAS",
            "rank": 46,
            "name": "Coolblue",
            "bucket": "API Pursuits Target",
            "country": "Netherlands",
            "segment": "Enterprise",
            "vertical": "Technology & Software Development",
            "owner": "Vinayak Mitra",
            "execSponsor": "Folley Ogundele",
            "arr": 20054,
            "pipeline": 0,
            "quarter": "Owned since 2023-11-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000CoWYrYAN",
            "rank": 47,
            "name": "Terveystalo Healthcare Oy",
            "bucket": "API Pursuits Target",
            "country": "Finland",
            "segment": "Enterprise",
            "vertical": "Healthcare & Life Sciences",
            "owner": "Kofi Ankomah",
            "execSponsor": "Folley Ogundele",
            "arr": 19801,
            "pipeline": 0,
            "quarter": "Owned since 2026-02-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000CoJ0jYAF",
            "rank": 48,
            "name": "Exasol AG",
            "bucket": "API Pursuits Target",
            "country": "Germany",
            "segment": "Startups",
            "vertical": "Technology & Software Development",
            "owner": "Amaury de Longvilliers",
            "execSponsor": "Chris Brown",
            "arr": 38,
            "pipeline": 0,
            "quarter": "Owned since 2025-11-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000CoD6ZYAV",
            "rank": 49,
            "name": "PM Computer Services GmbH & Co. KG",
            "bucket": "API Pursuits Target",
            "country": "Germany",
            "segment": "Digital Natives",
            "vertical": "Technology & Software Development",
            "owner": "Niklas Harzheim",
            "execSponsor": "Clement Andre",
            "arr": 0,
            "pipeline": 0,
            "quarter": "Owned since 2026-04-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "API Pursuits Target",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000E3ha2YAB",
            "rank": 50,
            "name": "Lefebvre Sarrut",
            "bucket": "MM Top Expansion",
            "country": "France",
            "segment": "Mid-Market",
            "vertical": "Technology & Software Development",
            "owner": "Claire Trithardt",
            "execSponsor": "Orian English",
            "arr": 3464882,
            "pipeline": 0,
            "quarter": "Owned since 2024-11-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Azure OpenAI Service",
            "flags": []
        },
        {
            "accountId": "001VU00000KlI7kYAF",
            "rank": 51,
            "name": "CHECK24",
            "bucket": "MM Top Expansion",
            "country": "Germany",
            "segment": "Digital Natives",
            "vertical": "N/A",
            "owner": "Tilman Resch",
            "execSponsor": "Phil Watson",
            "arr": 1372757,
            "pipeline": 0,
            "quarter": "Owned since 2025-03-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000qejpPAAQ",
            "rank": 52,
            "name": "Marshall Wace Asset Management Ltd",
            "bucket": "MM Top Expansion",
            "country": "United Kingdom",
            "segment": "Mid-Market",
            "vertical": "Financial Services",
            "owner": "Charly Deighton",
            "execSponsor": "Orian English",
            "arr": 1258559,
            "pipeline": 0,
            "quarter": "Owned since 2023-04-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Azure OpenAI Service",
            "flags": []
        },
        {
            "accountId": "001VU000004fGePYAU",
            "rank": 53,
            "name": "H. Lundbeck A/S",
            "bucket": "MM Top Expansion",
            "country": "Denmark",
            "segment": "Enterprise",
            "vertical": "Healthcare & Life Sciences",
            "owner": "Kofi Ankomah",
            "execSponsor": "Folley Ogundele",
            "arr": 944100,
            "pipeline": 0,
            "quarter": "Owned since 2024-09-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000HsWUBYA3",
            "rank": 54,
            "name": "CTS Eventim AG & Co. KGaA",
            "bucket": "MM Top Expansion",
            "country": "Germany",
            "segment": "Mid-Market",
            "vertical": "Other",
            "owner": "Johannes Foertsch",
            "execSponsor": "Orian English",
            "arr": 852121,
            "pipeline": 0,
            "quarter": "Owned since 2025-02-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000nUWCGAA4",
            "rank": 55,
            "name": "Baillie Gifford & co",
            "bucket": "MM Top Expansion",
            "country": "United Kingdom",
            "segment": "Mid-Market",
            "vertical": "Financial Services",
            "owner": "Helena Bunney",
            "execSponsor": "Orian English",
            "arr": 790779,
            "pipeline": 0,
            "quarter": "Owned since 2023-01-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000GEMnTYAX",
            "rank": 56,
            "name": "Syensqo SA",
            "bucket": "MM Top Expansion",
            "country": "Belgium",
            "segment": "Enterprise",
            "vertical": "Manufacturing / Construction",
            "owner": "Kofi Ankomah",
            "execSponsor": "Folley Ogundele",
            "arr": 522247,
            "pipeline": 0,
            "quarter": "Owned since 2025-08-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU000006kmqzYAA",
            "rank": 57,
            "name": "ETORO LTD",
            "bucket": "MM Top Expansion",
            "country": "Israel",
            "segment": "Digital Natives",
            "vertical": "Financial Services",
            "owner": "Claire Harrington",
            "execSponsor": "Phil Watson",
            "arr": 497218,
            "pipeline": 500000,
            "quarter": "2026-09-03 — EToro-[API cross-sell, Azure compete]-$500k",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "ChatGPT PQA;MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000ISs3UYAT",
            "rank": 58,
            "name": "Beyon B.S.C.",
            "bucket": "MM Top Expansion",
            "country": "Bahrain",
            "segment": "Mid-Market",
            "vertical": "Technology & Software Development",
            "owner": "Kurtis Patterson",
            "execSponsor": "Orian English",
            "arr": 432000,
            "pipeline": 0,
            "quarter": "Owned since 2024-12-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0014X00002iFjBbQAK",
            "rank": 59,
            "name": "Two Circles",
            "bucket": "MM Top Expansion",
            "country": "United Kingdom",
            "segment": "Mid-Market",
            "vertical": "Media & Telecom",
            "owner": "Orian English",
            "execSponsor": "Sanj Bhayro",
            "arr": 355656,
            "pipeline": 0,
            "quarter": "Owned since 2023-11-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000lCrNvAAK",
            "rank": 60,
            "name": "The Economist Newspaper Limited",
            "bucket": "MM Top Expansion",
            "country": "United Kingdom",
            "segment": "Mid-Market",
            "vertical": "Media & Telecom",
            "owner": "Kurtis Patterson",
            "execSponsor": "Orian English",
            "arr": 285293,
            "pipeline": 0,
            "quarter": "Owned since 2023-12-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0014X00002hivm5QAA",
            "rank": 61,
            "name": "Capital Fund Management",
            "bucket": "MM Top Expansion",
            "country": "France",
            "segment": "Mid-Market",
            "vertical": "Financial Services",
            "owner": "Claire Trithardt",
            "execSponsor": "Orian English",
            "arr": 272114,
            "pipeline": 0,
            "quarter": "Owned since 2024-05-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion;FY26 Hedge Fund Carveout;FY26 Hedge Fund Carveout",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000EKuduYAD",
            "rank": 62,
            "name": "Abu Dhabi Investment Council Company PJSC",
            "bucket": "MM Top Expansion",
            "country": "United Arab Emirates",
            "segment": "Mid-Market",
            "vertical": "Financial Services",
            "owner": "John Shanahan",
            "execSponsor": "Orian English",
            "arr": 261208,
            "pipeline": 0,
            "quarter": "Owned since 2025-03-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion;FY26 Hedge Fund Carveout;FY26 Hedge Fund Carveout",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU000009ronuYAA",
            "rank": 63,
            "name": "Solina Group Services",
            "bucket": "MM Top Expansion",
            "country": "France",
            "segment": "Mid-Market",
            "vertical": "Manufacturing / Construction",
            "owner": "Claire Trithardt",
            "execSponsor": "Orian English",
            "arr": 259200,
            "pipeline": 0,
            "quarter": "Owned since 2025-03-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000EahBGYAZ",
            "rank": 64,
            "name": "Ambea Sverige AB",
            "bucket": "MM Top Expansion",
            "country": "Sweden",
            "segment": "Enterprise",
            "vertical": "Healthcare & Life Sciences",
            "owner": "Stephanie Tran",
            "execSponsor": "Nico Skabo",
            "arr": 240000,
            "pipeline": 0,
            "quarter": "Owned since 2025-01-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000JcfdVYAR",
            "rank": 65,
            "name": "Fibabanka",
            "bucket": "MM Top Expansion",
            "country": "Türkiye",
            "segment": "Mid-Market",
            "vertical": "N/A",
            "owner": "Charly Deighton",
            "execSponsor": "Orian English",
            "arr": 237600,
            "pipeline": 0,
            "quarter": "Owned since 2025-04-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000qeVfAAAU",
            "rank": 66,
            "name": "Talpa Network",
            "bucket": "MM Top Expansion",
            "country": "Netherlands",
            "segment": "Mid-Market",
            "vertical": "Media & Telecom",
            "owner": "Guillermo Kirkpatrick Molgo",
            "execSponsor": "Orian English",
            "arr": 227295,
            "pipeline": 0,
            "quarter": "Owned since 2024-02-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU000007Nf01YAC",
            "rank": 67,
            "name": "RHI Magnesita GmbH",
            "bucket": "MM Top Expansion",
            "country": "Austria",
            "segment": "Enterprise",
            "vertical": "Manufacturing / Construction",
            "owner": "Kevin Gehrmann",
            "execSponsor": "Nico Skabo",
            "arr": 218892,
            "pipeline": 0,
            "quarter": "Owned since 2025-01-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "ChatGPT PQA;MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000GubuwYAB",
            "rank": 68,
            "name": "Leica Camera AG",
            "bucket": "MM Top Expansion",
            "country": "Germany",
            "segment": "Mid-Market",
            "vertical": "Other",
            "owner": "Johannes Foertsch",
            "execSponsor": "Orian English",
            "arr": 216000,
            "pipeline": 0,
            "quarter": "Owned since 2025-04-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000QDvMUYA1",
            "rank": 69,
            "name": "HgCapital LLP",
            "bucket": "MM Top Expansion",
            "country": "United Kingdom",
            "segment": "Mid-Market",
            "vertical": "Financial Services",
            "owner": "Charly Deighton",
            "execSponsor": "Orian English",
            "arr": 204000,
            "pipeline": 0,
            "quarter": "Owned since 2025-10-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000HOxUzYAL",
            "rank": 70,
            "name": "Uria Menendez Abogados SLP",
            "bucket": "MM Top Expansion",
            "country": "Spain",
            "segment": "Mid-Market",
            "vertical": "Other",
            "owner": "Guillermo Kirkpatrick Molgo",
            "execSponsor": "Orian English",
            "arr": 192000,
            "pipeline": 0,
            "quarter": "Owned since 2025-02-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0014X00002iGPXeQAO",
            "rank": 71,
            "name": "Permira Advisers (London) Limited",
            "bucket": "MM Top Expansion",
            "country": "United Kingdom",
            "segment": "Mid-Market",
            "vertical": "Financial Services",
            "owner": "Charly Deighton",
            "execSponsor": "Orian English",
            "arr": 186624,
            "pipeline": 0,
            "quarter": "Owned since 2025-06-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "Tier 1 P.E.;Tier 1 P.E.;MM Top Expansion;FY26 PE Carveout;FY26 PE Carveout",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000MlfF0YAJ",
            "rank": 72,
            "name": "Arrow Global Group",
            "bucket": "MM Top Expansion",
            "country": "United Kingdom",
            "segment": "Mid-Market",
            "vertical": "N/A",
            "owner": "Charly Deighton",
            "execSponsor": "Orian English",
            "arr": 173862,
            "pipeline": 48204,
            "quarter": "2026-04-30 — Renewal [2026] - Arrow Global - ChatGPT Enterprise",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000OgPU2YAN",
            "rank": 73,
            "name": "Ontic Engineering and Manufacturing Ltd",
            "bucket": "MM Top Expansion",
            "country": "United Kingdom",
            "segment": "Mid-Market",
            "vertical": "N/A",
            "owner": "Kurtis Patterson",
            "execSponsor": "Orian English",
            "arr": 169179,
            "pipeline": 8904,
            "quarter": "2026-07-06 — Renewal [2026] - Ontic - ChatGPT Enterprise",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000R2HbVYAV",
            "rank": 74,
            "name": "The UK Branch of Awaze A/S",
            "bucket": "MM Top Expansion",
            "country": "United Kingdom",
            "segment": "Mid-Market",
            "vertical": "N/A",
            "owner": "Helena Bunney",
            "execSponsor": "Orian English",
            "arr": 162144,
            "pipeline": 0,
            "quarter": "Owned since 2025-06-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000hugVYAAY",
            "rank": 75,
            "name": "Dept Holding B.V",
            "bucket": "MM Top Expansion",
            "country": "Netherlands",
            "segment": "Mid-Market",
            "vertical": "Media & Telecom",
            "owner": "John Shanahan",
            "execSponsor": "Orian English",
            "arr": 158569,
            "pipeline": 960,
            "quarter": "2026-04-25 — Renewal [2026] - DEPT US Holding Inc - Renewal",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000GhaGnYAJ",
            "rank": 76,
            "name": "BAMA Gruppen AS",
            "bucket": "MM Top Expansion",
            "country": "Norway",
            "segment": "Mid-Market",
            "vertical": "Retail & Consumer Goods",
            "owner": "Orian English",
            "execSponsor": "Sanj Bhayro",
            "arr": 148680,
            "pipeline": 0,
            "quarter": "Owned since 2025-02-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000OxnQIYAZ",
            "rank": 77,
            "name": "Sophos Limited",
            "bucket": "MM Top Expansion",
            "country": "United Kingdom",
            "segment": "Mid-Market",
            "vertical": "N/A",
            "owner": "Sean McKeon",
            "execSponsor": "Orian English",
            "arr": 141007,
            "pipeline": 0,
            "quarter": "Owned since 2023-08-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000BAqtSYAT",
            "rank": 78,
            "name": "Cyprus Telecommunications Authority",
            "bucket": "MM Top Expansion",
            "country": "Cyprus",
            "segment": "Mid-Market",
            "vertical": "Media & Telecom",
            "owner": "Charly Deighton",
            "execSponsor": "Orian English",
            "arr": 139354,
            "pipeline": 0,
            "quarter": "Owned since 2025-01-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000JgrjKYAR",
            "rank": 79,
            "name": "mylife Diabetes Care AG",
            "bucket": "MM Top Expansion",
            "country": "Switzerland",
            "segment": "Mid-Market",
            "vertical": "N/A",
            "owner": "Sarah Kemether",
            "execSponsor": "Orian English",
            "arr": 139200,
            "pipeline": 0,
            "quarter": "Owned since 2025-02-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000Mx97UYAR",
            "rank": 80,
            "name": "Aurubis AG",
            "bucket": "MM Top Expansion",
            "country": "Germany",
            "segment": "Enterprise",
            "vertical": "Manufacturing / Construction",
            "owner": "Christoph Winter",
            "execSponsor": "Nico Skabo",
            "arr": 109968,
            "pipeline": 0,
            "quarter": "Owned since 2025-06-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000PSE8BYAX",
            "rank": 81,
            "name": "Lucta, S.A. (A08074908)",
            "bucket": "MM Top Expansion",
            "country": "Spain",
            "segment": "Mid-Market",
            "vertical": "N/A",
            "owner": "Guillermo Kirkpatrick Molgo",
            "execSponsor": "Orian English",
            "arr": 109440,
            "pipeline": 0,
            "quarter": "Owned since 2025-05-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000KxFh3YAF",
            "rank": 82,
            "name": "Lombardi SA",
            "bucket": "MM Top Expansion",
            "country": "Switzerland",
            "segment": "Mid-Market",
            "vertical": "Manufacturing / Construction",
            "owner": "Johannes Foertsch",
            "execSponsor": "Orian English",
            "arr": 105607,
            "pipeline": 0,
            "quarter": "Owned since 2025-04-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000dfobxYAA",
            "rank": 83,
            "name": "SER Group Holding International GmbH",
            "bucket": "MM Top Expansion",
            "country": "Germany",
            "segment": "Mid-Market",
            "vertical": "N/A",
            "owner": "Johannes Foertsch",
            "execSponsor": "Orian English",
            "arr": 99000,
            "pipeline": 0,
            "quarter": "Owned since 2026-01-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU000002hMAbYAM",
            "rank": 84,
            "name": "Paris Saint-Germain (PSG)",
            "bucket": "MM Top Expansion",
            "country": "France",
            "segment": "Mid-Market",
            "vertical": "Media & Telecom",
            "owner": "Claire Trithardt",
            "execSponsor": "Orian English",
            "arr": 91468,
            "pipeline": 0,
            "quarter": "Owned since 2025-03-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0015e00000tiRzkAAE",
            "rank": 85,
            "name": "Collinson (Central Services) Limited",
            "bucket": "MM Top Expansion",
            "country": "United Kingdom",
            "segment": "Mid-Market",
            "vertical": "Other",
            "owner": "Helena Bunney",
            "execSponsor": "Orian English",
            "arr": 89329,
            "pipeline": 0,
            "quarter": "Owned since 2025-04-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000H9sdjYAB",
            "rank": 86,
            "name": "MarineMax Superyachts Monaco",
            "bucket": "MM Top Expansion",
            "country": "United States of America",
            "segment": "Mid-Market",
            "vertical": "Other",
            "owner": "Orian English",
            "execSponsor": "Sanj Bhayro",
            "arr": 87366,
            "pipeline": 0,
            "quarter": "Owned since 2025-01-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000HdUR3YAN",
            "rank": 87,
            "name": "Elemis, Limited",
            "bucket": "MM Top Expansion",
            "country": "United Kingdom",
            "segment": "Mid-Market",
            "vertical": "Other",
            "owner": "Orian English",
            "execSponsor": "Sanj Bhayro",
            "arr": 87003,
            "pipeline": 0,
            "quarter": "Owned since 2025-03-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "0014X00002hjjk9QAA",
            "rank": 88,
            "name": "LCP",
            "bucket": "MM Top Expansion",
            "country": "United Kingdom",
            "segment": "Mid-Market",
            "vertical": "Financial Services",
            "owner": "Kurtis Patterson",
            "execSponsor": "Orian English",
            "arr": 84141,
            "pipeline": 0,
            "quarter": "Owned since 2025-06-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000ESkHkYAL",
            "rank": 89,
            "name": "Engel & Völkers Technology GmbH",
            "bucket": "MM Top Expansion",
            "country": "United Arab Emirates",
            "segment": "Mid-Market",
            "vertical": "Other",
            "owner": "Helena Bunney",
            "execSponsor": "Orian English",
            "arr": 78433,
            "pipeline": 0,
            "quarter": "Owned since 2025-11-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000GmHAOYA3",
            "rank": 90,
            "name": "MyHeritage",
            "bucket": "MM Top Expansion",
            "country": "Israel",
            "segment": "Mid-Market",
            "vertical": "Technology & Software Development",
            "owner": "Charly Deighton",
            "execSponsor": "Orian English",
            "arr": 72990,
            "pipeline": 0,
            "quarter": "Owned since 2024-11-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000EqLTKYA3",
            "rank": 91,
            "name": "KX Systems Inc",
            "bucket": "MM Top Expansion",
            "country": "United States of America",
            "segment": "Mid-Market",
            "vertical": "Technology & Software Development",
            "owner": "Orian English",
            "execSponsor": "Sanj Bhayro",
            "arr": 72960,
            "pipeline": 0,
            "quarter": "Owned since 2025-01-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000MXGe2YAH",
            "rank": 92,
            "name": "Grupo Ferrer Internacional, S.A.",
            "bucket": "MM Top Expansion",
            "country": "Spain",
            "segment": "Mid-Market",
            "vertical": "N/A",
            "owner": "Guillermo Kirkpatrick Molgo",
            "execSponsor": "Orian English",
            "arr": 72000,
            "pipeline": 0,
            "quarter": "Owned since 2025-07-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000PjsQvYAJ",
            "rank": 93,
            "name": "T F G Real Estate LLC",
            "bucket": "MM Top Expansion",
            "country": "United Arab Emirates",
            "segment": "Mid-Market",
            "vertical": "N/A",
            "owner": "Helena Bunney",
            "execSponsor": "Orian English",
            "arr": 72000,
            "pipeline": 0,
            "quarter": "Owned since 2025-06-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000EOw1DYAT",
            "rank": 94,
            "name": "Accuracy",
            "bucket": "MM Top Expansion",
            "country": "France",
            "segment": "Mid-Market",
            "vertical": "Financial Services",
            "owner": "Claire Trithardt",
            "execSponsor": "Orian English",
            "arr": 58993,
            "pipeline": 0,
            "quarter": "2026-12-04 — Renewal [2026] - Accuracy-ChatLand",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "ChatGPT PQA;ChatGPT PQA;MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000P3cwvYAB",
            "rank": 95,
            "name": "Index Ventures (Jersey) Limited",
            "bucket": "MM Top Expansion",
            "country": "United Kingdom",
            "segment": "Mid-Market",
            "vertical": "N/A",
            "owner": "Charly Deighton",
            "execSponsor": "Orian English",
            "arr": 48000,
            "pipeline": 0,
            "quarter": "Owned since 2025-05-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000chzojYAA",
            "rank": 96,
            "name": "GEISLINGER GMBH",
            "bucket": "MM Top Expansion",
            "country": "Austria",
            "segment": "Mid-Market",
            "vertical": "N/A",
            "owner": "Sarah Kemether",
            "execSponsor": "Orian English",
            "arr": 44748,
            "pipeline": 0,
            "quarter": "Owned since 2025-11-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000fvCZXYA2",
            "rank": 97,
            "name": "TMV Capital",
            "bucket": "MM Top Expansion",
            "country": "Canada",
            "segment": "Mid-Market",
            "vertical": "N/A",
            "owner": "John Shanahan",
            "execSponsor": "Orian English",
            "arr": 39600,
            "pipeline": 0,
            "quarter": "Owned since 2026-01-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000Wb0OSYAZ",
            "rank": 98,
            "name": "Alois Müller Holding GmbH & Co. KG",
            "bucket": "MM Top Expansion",
            "country": "Germany",
            "segment": "SMB",
            "vertical": "Manufacturing / Construction",
            "owner": "Charly Deighton",
            "execSponsor": "Orian English",
            "arr": 34848,
            "pipeline": 0,
            "quarter": "Owned since 2025-09-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000K2I0YYAV",
            "rank": 99,
            "name": "Ahlsell Sverige AB",
            "bucket": "MM Top Expansion",
            "country": "Sweden",
            "segment": "Mid-Market",
            "vertical": "Manufacturing / Construction",
            "owner": "Kofi Ankomah",
            "execSponsor": "Folley Ogundele",
            "arr": 24000,
            "pipeline": 0,
            "quarter": "Owned since 2025-05-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        },
        {
            "accountId": "001VU00000FDvsfYAD",
            "rank": 100,
            "name": "Aldar Properties Pjsc",
            "bucket": "MM Top Expansion",
            "country": "United Arab Emirates",
            "segment": "Mid-Market",
            "vertical": "Other",
            "owner": "Sean McKeon",
            "execSponsor": "Orian English",
            "arr": 24000,
            "pipeline": 0,
            "quarter": "Owned since 2025-09-01",
            "sourceType": "Kepler live query",
            "sourceSnapshotDate": "2026-04-14",
            "lastRefreshedAt": "2026-04-16 19:14:23 UTC",
            "accountTag": "MM Top Expansion",
            "competitiveRisk": "Unknown",
            "flags": []
        }
    ]
},
  geos: [
    { geo: "North", totalAccounts: 3235, accountsInBooks: 1913, currentCoverage: 0.5913446677, recommendedCoverage: 0.7874188563, incrementalAccounts: 634.3, recommendedAds: 48, arr: 196906011.12, customers: 414, managers: 7 },
    { geo: "Central", totalAccounts: 2034, accountsInBooks: 1135, currentCoverage: 0.558013766, recommendedCoverage: 0.7194690265, incrementalAccounts: 328.4, recommendedAds: 27, arr: 65427451.06, customers: 225, managers: 4 },
    { geo: "South", totalAccounts: 2072, accountsInBooks: 1042, currentCoverage: 0.5028957529, recommendedCoverage: 0.661969112, incrementalAccounts: 329.6, recommendedAds: 24, arr: 51275028.21, customers: 159, managers: 4 },
    { geo: "MEA", totalAccounts: 1072, accountsInBooks: 453, currentCoverage: 0.4225746269, recommendedCoverage: 0.6179104478, incrementalAccounts: 209.4, recommendedAds: 12, arr: 8703789.18, customers: 45, managers: 2 }
  ],
  tiers: [
    { tier: "Tier 1", totalAccounts: 3948, accountsInBooks: 2175, currentCoverage: 0.5509118541, recommendedCoverage: 0.7387537994, incrementalAccounts: 741.6, recommendedAds: 60, arr: 150792675.53 },
    { tier: "Tier 2", totalAccounts: 2243, accountsInBooks: 1250, currentCoverage: 0.5572893446, recommendedCoverage: 0.7195720018, incrementalAccounts: 364, recommendedAds: 29, arr: 121347218.61 },
    { tier: "Tier 3", totalAccounts: 1211, accountsInBooks: 645, currentCoverage: 0.5326176713, recommendedCoverage: 0.7003303055, incrementalAccounts: 203.1, recommendedAds: 11, arr: 29399869.06 },
    { tier: "Tier 4", totalAccounts: 1011, accountsInBooks: 473, currentCoverage: 0.4678536103, recommendedCoverage: 0.6587537092, incrementalAccounts: 193, recommendedAds: 11, arr: 20772516.37 }
  ],
  territories: [
    { tier: "Tier 1", geo: "North", territory: "UKI", totalAccounts: 1754, accountsInBooks: 987, currentCoverage: 0.562713797, recommendedCoverage: 0.7751425314, incrementalAccounts: 372.6, recommendedAds: 28, targetAccountsPerAd: 48.55714286, arr: 103846608.07, arrGrowth: 1.649698697, customers: 222, arrPerCustomer: 467777.5138, segmentAds: { "Large Enterprise": 6, Enterprise: 6, "Digital Natives": 12, "Mid-Market": 4 } },
    { tier: "Tier 1", geo: "Central", territory: "Germany", totalAccounts: 1148, accountsInBooks: 650, currentCoverage: 0.5662020906, recommendedCoverage: 0.7275261324, incrementalAccounts: 185.2, recommendedAds: 17, targetAccountsPerAd: 49.12941176, arr: 30812841.76, arrGrowth: 5.288376415, customers: 123, arrPerCustomer: 250510.9086, segmentAds: { "Large Enterprise": 4, Enterprise: 4, "Digital Natives": 7, "Mid-Market": 2 } },
    { tier: "Tier 1", geo: "South", territory: "France", totalAccounts: 1046, accountsInBooks: 538, currentCoverage: 0.5143403442, recommendedCoverage: 0.6900573614, incrementalAccounts: 183.8, recommendedAds: 15, targetAccountsPerAd: 48.12, arr: 16133225.7, arrGrowth: 4.178967067, customers: 69, arrPerCustomer: 233814.8652, segmentAds: { "Large Enterprise": 6, Enterprise: 3, "Digital Natives": 3, "Mid-Market": 3 } },
    { tier: "Tier 2", geo: "North", territory: "Netherlands/Belgium/Luxembourg", totalAccounts: 721, accountsInBooks: 438, currentCoverage: 0.6074895978, recommendedCoverage: 0.7922330097, incrementalAccounts: 133.2, recommendedAds: 10, targetAccountsPerAd: 57.12, arr: 28249788.68, arrGrowth: 1.968647851, customers: 72, arrPerCustomer: 392358.1761, segmentAds: { "Large Enterprise": 2, Enterprise: 3, "Digital Natives": 3, "Mid-Market": 2 } },
    { tier: "Tier 2", geo: "North", territory: "Sweden", totalAccounts: 331, accountsInBooks: 209, currentCoverage: 0.6314199396, recommendedCoverage: 0.813897281, incrementalAccounts: 60.4, recommendedAds: 5, targetAccountsPerAd: 53.88, arr: 41534163.75, arrGrowth: 2.355039541, customers: 50, arrPerCustomer: 830683.275, segmentAds: { "Large Enterprise": 1, Enterprise: 1, "Digital Natives": 2, "Mid-Market": 1 } },
    { tier: "Tier 2", geo: "Central", territory: "Switzerland/Austria", totalAccounts: 508, accountsInBooks: 283, currentCoverage: 0.5570866142, recommendedCoverage: 0.7033464567, incrementalAccounts: 74.3, recommendedAds: 6, targetAccountsPerAd: 59.55, arr: 22257726.41, arrGrowth: 8.578422161, customers: 56, arrPerCustomer: 397459.4002, segmentAds: { "Large Enterprise": 2, Enterprise: 1, "Digital Natives": 2, "Mid-Market": 1 } },
    { tier: "Tier 2", geo: "South", territory: "Spain", totalAccounts: 428, accountsInBooks: 209, currentCoverage: 0.488317757, recommendedCoverage: 0.608411215, incrementalAccounts: 51.4, recommendedAds: 4, targetAccountsPerAd: 65.1, arr: 27134100.68, arrGrowth: 5.196716801, customers: 47, arrPerCustomer: 577321.2911, segmentAds: { "Large Enterprise": 1, Enterprise: 1, "Digital Natives": 1, "Mid-Market": 1 } },
    { tier: "Tier 2", geo: "MEA", territory: "UAE", totalAccounts: 255, accountsInBooks: 111, currentCoverage: 0.4352941176, recommendedCoverage: 0.6105882353, incrementalAccounts: 44.7, recommendedAds: 4, targetAccountsPerAd: 38.925, arr: 2171439.09, arrGrowth: 1.160040083, customers: 18, arrPerCustomer: 120635.505, segmentAds: { "Large Enterprise": 1, Enterprise: 1, "Digital Natives": 1, "Mid-Market": 1 } },
    { tier: "Tier 3", geo: "North", territory: "Israel", totalAccounts: 113, accountsInBooks: 70, currentCoverage: 0.6194690265, recommendedCoverage: 0.7619469027, incrementalAccounts: 16.1, recommendedAds: 1, targetAccountsPerAd: 86.1, arr: 12978535.11, arrGrowth: 1.771052715, customers: 30, arrPerCustomer: 432617.837, segmentAds: { "Large Enterprise": 0, Enterprise: 0, "Digital Natives": 1, "Mid-Market": 0 } },
    { tier: "Tier 3", geo: "North", territory: "Norway/Denmark", totalAccounts: 316, accountsInBooks: 209, currentCoverage: 0.6613924051, recommendedCoverage: 0.8259493671, incrementalAccounts: 52, recommendedAds: 4, targetAccountsPerAd: 65.25, arr: 10296915.51, arrGrowth: 1.26049856, customers: 40, arrPerCustomer: 257422.8878, segmentAds: { "Large Enterprise": 1, Enterprise: 1, "Digital Natives": 1, "Mid-Market": 1 } },
    { tier: "Tier 3", geo: "Central", territory: "Poland", totalAccounts: 132, accountsInBooks: 68, currentCoverage: 0.5151515152, recommendedCoverage: 0.725, incrementalAccounts: 27.7, recommendedAds: 1, targetAccountsPerAd: 95.7, arr: 2082145.78, arrGrowth: 0.1925345849, customers: 11, arrPerCustomer: 189285.98, segmentAds: { "Large Enterprise": 0, Enterprise: 0, "Digital Natives": 1, "Mid-Market": 0 } },
    { tier: "Tier 3", geo: "South", territory: "Italy", totalAccounts: 450, accountsInBooks: 220, currentCoverage: 0.4888888889, recommendedCoverage: 0.6406666667, incrementalAccounts: 68.3, recommendedAds: 4, targetAccountsPerAd: 72.075, arr: 2944182.6, arrGrowth: 1.829615541, customers: 23, arrPerCustomer: 128007.9391, segmentAds: { "Large Enterprise": 1, Enterprise: 1, "Digital Natives": 1, "Mid-Market": 1 } },
    { tier: "Tier 3", geo: "MEA", territory: "Saudi Arabia/Qatar", totalAccounts: 200, accountsInBooks: 78, currentCoverage: 0.39, recommendedCoverage: 0.585, incrementalAccounts: 39, recommendedAds: 1, targetAccountsPerAd: 117, arr: 1098090.06, arrGrowth: 0.8781924793, customers: 5, arrPerCustomer: 219618.012, segmentAds: { "Large Enterprise": 0, Enterprise: 0, "Digital Natives": 1, "Mid-Market": 0 } },
    { tier: "Tier 4", geo: "Central", territory: "Rest of Central", totalAccounts: 246, accountsInBooks: 134, currentCoverage: 0.5447154472, recommendedCoverage: 0.712195122, incrementalAccounts: 41.2, recommendedAds: 3, targetAccountsPerAd: 58.4, arr: 10274737.11, arrGrowth: -0.4920581716, customers: 35, arrPerCustomer: 293563.9174, segmentAds: { "Large Enterprise": 0, Enterprise: 0, "Digital Natives": 2, "Mid-Market": 1 } },
    { tier: "Tier 4", geo: "South", territory: "Rest of South", totalAccounts: 148, accountsInBooks: 75, currentCoverage: 0.5067567568, recommendedCoverage: 0.6831081081, incrementalAccounts: 26.1, recommendedAds: 1, targetAccountsPerAd: 101.1, arr: 5063519.23, arrGrowth: 1.506262479, customers: 20, arrPerCustomer: 253175.9615, segmentAds: { "Large Enterprise": 0, Enterprise: 0, "Digital Natives": 1, "Mid-Market": 0 } },
    { tier: "Tier 4", geo: "MEA", territory: "Rest of MEA", totalAccounts: 617, accountsInBooks: 264, currentCoverage: 0.4278768233, recommendedCoverage: 0.6316045381, incrementalAccounts: 125.7, recommendedAds: 7, targetAccountsPerAd: 55.67142857, arr: 5434260.03, arrGrowth: 2.198933723, customers: 22, arrPerCustomer: 247011.8195, segmentAds: { "Large Enterprise": 1, Enterprise: 2, "Digital Natives": 2, "Mid-Market": 2 } }
  ],
  segmentDetails: [
    { geo: "North", territory: "UKI", segment: "Large Enterprise", tier: "Tier 1", arr: 32290893.93, customers: 15, totalAccounts: 115, whitespace: 29, ads: 6 },
    { geo: "North", territory: "UKI", segment: "Enterprise", tier: "Tier 1", arr: 18022279.89, customers: 44, totalAccounts: 471, whitespace: 81, ads: 6 },
    { geo: "North", territory: "UKI", segment: "Digital Natives", tier: "Tier 1", arr: 35874168.47, customers: 75, totalAccounts: 509, whitespace: 145.5, ads: 12 },
    { geo: "North", territory: "UKI", segment: "Mid-Market", tier: "Tier 1", arr: 17659265.78, customers: 88, totalAccounts: 659, whitespace: 117.1, ads: 4 },
    { geo: "Central", territory: "Germany", segment: "Large Enterprise", tier: "Tier 1", arr: 11248814.51, customers: 9, totalAccounts: 79, whitespace: 18.5, ads: 4 },
    { geo: "Central", territory: "Germany", segment: "Enterprise", tier: "Tier 1", arr: 2756635.88, customers: 32, totalAccounts: 396, whitespace: 58, ads: 4 },
    { geo: "Central", territory: "Germany", segment: "Digital Natives", tier: "Tier 1", arr: 9015879.97, customers: 32, totalAccounts: 282, whitespace: 69.8, ads: 7 },
    { geo: "South", territory: "France", segment: "Large Enterprise", tier: "Tier 1", arr: 3046052.89, customers: 9, totalAccounts: 97, whitespace: 28.3, ads: 6 },
    { geo: "South", territory: "France", segment: "Mid-Market", tier: "Tier 1", arr: 7262443.11, customers: 34, totalAccounts: 460, whitespace: 82, ads: 3 },
    { geo: "MEA", territory: "Rest of MEA", segment: "Mid-Market", tier: "Tier 4", arr: 1542187.99, customers: 11, totalAccounts: 293, whitespace: 83.7, ads: 2 }
  ],
  segmentCapacity: [
    { geo: "North", segment: "Enterprise", currentAds: 10, whitespace: 205.8, customers: 108, arr: 63417137.5, totalAccounts: 1056, recommendedAds: 21, gapAds: 11 },
    { geo: "North", segment: "Digital Natives", currentAds: 9, whitespace: 228.2, customers: 127, arr: 96012474.87, totalAccounts: 822, recommendedAds: 19, gapAds: 10 },
    { geo: "North", segment: "Mid-Market", currentAds: 8, whitespace: 200.3, customers: 179, arr: 37476398.75, totalAccounts: 1357, recommendedAds: 8, gapAds: 0 },
    { geo: "Central", segment: "Enterprise", currentAds: 7, whitespace: 118.5, customers: 63, arr: 31515084.97, totalAccounts: 802, recommendedAds: 11, gapAds: 4 },
    { geo: "Central", segment: "Digital Natives", currentAds: 4, whitespace: 114.5, customers: 64, arr: 21323109.82, totalAccounts: 485, recommendedAds: 12, gapAds: 8 },
    { geo: "Central", segment: "Mid-Market", currentAds: 3, whitespace: 95.4, customers: 98, arr: 12589256.27, totalAccounts: 747, recommendedAds: 4, gapAds: 1 },
    { geo: "South", segment: "Enterprise", currentAds: 5, whitespace: 98.8, customers: 44, arr: 28404669.57, totalAccounts: 751, recommendedAds: 13, gapAds: 8 },
    { geo: "South", segment: "Digital Natives", currentAds: 2, whitespace: 67.5, customers: 31, arr: 10096657.33, totalAccounts: 354, recommendedAds: 6, gapAds: 4 },
    { geo: "South", segment: "Mid-Market", currentAds: 4, whitespace: 163.3, customers: 84, arr: 12773701.31, totalAccounts: 967, recommendedAds: 5, gapAds: 1 },
    { geo: "MEA", segment: "Enterprise", currentAds: 1, whitespace: 39.5, customers: 12, arr: 2339905.94, totalAccounts: 394, recommendedAds: 5, gapAds: 4 },
    { geo: "MEA", segment: "Digital Natives", currentAds: 0, whitespace: 39.5, customers: 5, arr: 3244975.15, totalAccounts: 190, recommendedAds: 4, gapAds: 4 },
    { geo: "MEA", segment: "Mid-Market", currentAds: 0, whitespace: 130.4, customers: 28, arr: 3118908.09, totalAccounts: 488, recommendedAds: 3, gapAds: 3 }
  ],
  topAccounts: [
    { rank: 1, account: "AXA UK", territory: "UKI", vertical: "Financial Services", country: "United Kingdom", type: "Prospect", revenueB: 114.901, employees: 118239, arr: 0, owner: "SFDC Service Account" },
    { rank: 1, account: "Aldi Ireland", territory: "UKI", vertical: "Retail, CPG & Consumer", country: "Ireland", type: "Prospect", revenueB: 120, employees: 201361, arr: 0, owner: "SFDC Service Account" },
    { rank: 1, account: "Vedanta Group", territory: "UKI", vertical: "Manufacturing & Industrial", country: "United Kingdom", type: "Prospect", revenueB: 57.92374, employees: 97015, arr: 0, owner: "Vivek Gupta" },
    { rank: 3, account: "HSBC HOLDINGS PLC", territory: "UKI", vertical: "Financial Services", country: "United Kingdom", type: "Prospect", revenueB: 66.1, employees: 211304, arr: 0, owner: "Robert Huber" },
    { rank: 3, account: "Rio Tinto", territory: "UKI", vertical: "Manufacturing & Industrial", country: "United Kingdom", type: "Customer", revenueB: 53.658, employees: 55561, arr: 1612341, owner: "Rikki Gorman" },
    { rank: 4, account: "Unilever", territory: "UKI", vertical: "Retail, CPG & Consumer", country: "United Kingdom", type: "Customer", revenueB: 65.934852675, employees: 125000, arr: 480000, owner: "Rikki Gorman" },
    { rank: 1, account: "Allianz SE", territory: "Germany", vertical: "Financial Services", country: "Germany", type: "Prospect", revenueB: 195.086, employees: 156626, arr: 0, owner: "SFDC Service Account" },
    { rank: 1, account: "McKesson", territory: "Germany", vertical: "Retail, CPG & Consumer", country: "Germany", type: "Prospect", revenueB: 377.595, employees: 51000, arr: 0, owner: "SFDC Service Account" },
    { rank: 1, account: "Siemens", territory: "Germany", vertical: "Manufacturing & Industrial", country: "Germany", type: "Customer", revenueB: 88.708198114, employees: 327000, arr: 594000, owner: "Jovana Jordanova" },
    { rank: 1, account: "Allianz France", territory: "France", vertical: "Financial Services", country: "France", type: "Prospect", revenueB: 103.545, employees: 7705, arr: 0, owner: "SFDC Service Account" },
    { rank: 2, account: "LVMH Louis Vuitton Moet Hennessy", territory: "France", vertical: "Retail, CPG & Consumer", country: "France", type: "Prospect", revenueB: 100.084, employees: 215000, arr: 0, owner: "Matthieu Fouchard" },
    { rank: 1, account: "VINCI", territory: "France", vertical: "Manufacturing & Industrial", country: "France", type: "Prospect", revenueB: 78.62894768, employees: 285000, arr: 0, owner: "Matthieu Fouchard" }
  ]
};
